CREATE TABLE CLOTHSTOCK(
  PC_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  LOOM_ID BIGINT NOT NULL,
  EMP_ID BIGINT NOT NULL,
  ENTRY_DATE DATE NOT NULL,
  METRES_WEAVED DECIMAL(15,6) NOT NULL,
  TOTAL_METRES DECIMAL(15,6) NOT NULL,
  SALARY_PROCESS CHAR(1)   NOT NULL,
  DELIVERY_PROCESS CHAR(1)  NOT NULL
);
CREATE TABLE CLOTHTYPE(
  CLOTH_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(16) NOT NULL,
  PC_DESCRIPTION VARCHAR(35) NOT NULL,
  STATUS CHAR(1) NOT NULL
);
CREATE TABLE FACTORY(
  FACTORY_ID BIGINT PRIMARY KEY,
  NAME VARCHAR(16) NOT NULL,
  ADDRESS VARCHAR(105) NOT NULL
);
CREATE TABLE LOOM(
  LOOM_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FACTORY_ID BIGINT NOT NULL,
  NAME VARCHAR(16) NOT NULL 
);

CREATE TABLE EMPLOYEES(
  EMP_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(105),
  LAST_NAME VARCHAR(105),
  EMAIL_ADDRESS VARCHAR(105),
  ADDRESS VARCHAR(105),
  COUNTRY VARCHAR(32),
  STATE VARCHAR(12),
  PHONE_NUMBER VARCHAR(24),
  ID_NUMBER VARCHAR(24)
);

CREATE TABLE EMP_SALARY(
  BILL_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  BILL_DATE DATE NOT NULL,
  EMP_ID BIGINT NOT NULL,
  FACTORY_ID BIGINT NOT NULL,
  METRES_WEAVED DECIMAL(15,8) NOT NULL,
  AMOUNT_PAID DECIMAL(15,8) NOT NULL
);

CREATE TABLE ADVANCES(
  EMP_ID BIGINT NOT NULL PRIMARY KEY,
  ADVDATE DATE NOT NULL,
  AMOUNT_PAID DECIMAL(6,4) NOT NULL,
  AMOUNT_RECIVED DECIMAL(6,4) NOT NULL
);

ALTER TABLE LOOM ADD FOREIGN KEY (FACTORY_ID) REFERENCES FACTORY(FACTORY_ID);
--ALTER TABLE RESERVATION ADD FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID);
--ALTER TABLE RESERVATION ADD FOREIGN KEY (GUEST_ID) REFERENCES GUEST(GUEST_ID);
CREATE INDEX IDX_EMP_SALARY_ ON EMP_SALARY(BILL_DATE);
